# Generated by Django 3.2.4 on 2021-06-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_link', models.CharField(max_length=256, verbose_name='URL')),
                ('base_link', models.CharField(blank=True, max_length=256, null=True)),
                ('redirects', models.IntegerField(default=0, verbose_name='Number of redirects')),
                ('min_url_link', models.CharField(max_length=100, verbose_name='Shorten URL')),
            ],
        ),
    ]
