# Generated by Django 3.2.4 on 2021-06-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimizator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='base_link',
            field=models.CharField(default='', max_length=256, verbose_name='Base Url'),
            preserve_default=False,
        ),
    ]
